# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - build
  - deploy

cache:
  key: cache_yarn
  paths:
  - .cache_yarn

build_client:
  stage: build
  only:
   - master
  script:
    - yarn install --cache-folder ../.cache_yarn
    - npm run build-web
  artifacts:
    paths:
    - /node_modules

deploy_to_firebase:
 stage: deploy
 environment: production
 only:
  - master
 script:
  - npm install firebase-tools -g
  - firebase deploy --token $FIREBASE_TOKEN
