# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - build
  - deploy

cache:
  key: cache_yarn
  paths:
  - .cache_yarn

install_client:
  stage: install
  script:
    - cd yarn install --cache-folder ../.cache_yarn
  artifacts:
    paths:
    - node_modules

build_client:
  stage: build
  only:
   - master
  script:
    - npm run build-web
  artifacts:
    paths:
    - web/public

deploy_to_firebase:
 stage: deploy
 only:
  - master
 script:
  - yarn global add firebase-tools --cache-folder ../.cache_yarn
  - firebase deploy --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN
  dependencies:
  - install_client
  - build_client
