# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
  - deploy

build_client:
  stage: build
  only:
   - master
  script:
    - npm install
    - npm run build-web

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy_to_firebase:
 stage: deploy
 only:
  - master
 script:
  - npm install firebase-tools -g
  - firebase deploy --token $FIREBASE_TOKEN
