# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
 - npm install
 - npm install -g firebase-tools

stages:
  - deploy

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"

deploy_to_firebase:
  stage: deploy
 environment:
  name: production
 only:
  - master
 script:
  - firebase deploy --token $FIREBASE_TOKEN
